### ISSUE TITLE
数据面板和控制面板

### ISSUE THREAD

**Issue by Guo-Zhang** [quanttide/quanttide-specification-of-data-engineering#9]
微服务引擎等很多现代的云原生应用都把数据面板Data Panel和Control Panel分离，也就是把云的后端和前端分离。有两种命名方式：Provider和Controller，或者Data Panel和Control Panel。

数据模板主要是用来在云端存储必要的数据和密钥，以方便云端注册和运维机制的正常使用。数据面板可以使用Django等框架实现，可以命名为`quanttide-data-provider`，同时作为社区版。商业版可以依然遵循内部命名习惯。

控制面板可以用来管理本地和云端编排、运维、可观测性等我们的工程标准里专门定义的特性。控制面板可以使用Flutter等框架实现，可以命名为`quanttide-data-controller`，同时作为社区版。商业版可以依然遵循内部命名习惯。本地注册和运维时，可以直接使用开源版本。如果需要上云和使用我们的云的机制，或者其他的高级能力、比如和其他云打通的能力，则需要用我们二次开发的商业版。

**Comment by xiezipeng05** [comment]
此想法已废弃
